# CodeRabbit configuration
# Make reviews optional and less intrusive

# Only review when specifically requested
auto_review: false

# Reduce noise - only show important issues
reviews:
  level: "important" # Options: all, important, critical

# Don't review certain file types
ignore:
  - "*.min.js"
  - "*.min.css"
  - "node_modules/**"
  - "*.log"

# Only review specific file types for a website
include:
  - "*.html"
  - "*.css"
  - "*.js"
  - "*.md"

# Customize what to check
checks:
  security: true
  performance: true
  accessibility: true
  best_practices: true
  style: false # Turn off style nitpicking
