blank_issues_enabled: false
contact_links:
  - name: 💬 Discussions
    url: https://github.com/adigunners/adigunners.github.io/discussions
    about: Ask questions and discuss ideas
  - name: 📚 README
    url: https://github.com/adigunners/adigunners.github.io#readme
    about: Start here for project overview and docs
