name: Add issues and PRs to Project

on:
  issues:
    types: [opened, reopened, labeled]
  pull_request:
    types: [opened, reopened, ready_for_review]

permissions:
  contents: read
  issues: write
  pull-requests: write
  projects: write

jobs:
  add-to-project:
    runs-on: ubuntu-latest
    steps:
      - name: Add to project board
        uses: actions/add-to-project@v0.5.0
        with:
          project-url: https://github.com/users/adigunners/projects/1
          github-token: ${{ secrets.GITHUB_TOKEN }}
