name: Guard public repo
on:
  push:
    paths-ignore:
      - '.codex/**'
  pull_request:
    paths-ignore:
      - '.codex/**'
jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Scan for sensitive filenames
        run: |
          # Exclude docs/, .codex/, .agent-os/, .github/, and tests/
          matches=$(git ls-files \
            | grep -v -E '^(docs/|\.codex/|\.agent-os/|\.github/|tests/|tools/testing/)' \
            | grep -Ei '(TECHNICAL_DOCUMENTATION|SCORING_|SYSTEM_GUIDE|DEVELOPER_GUIDE|EMAIL_CONTROL_PANEL|COLLABORATION_GUIDE|CI_CD|RELEASE_CHECKLIST|TESTING|TESTING_REFERENCE|EMAIL_PRIZE_REFERENCE)' || true)
          if [ -n "$matches" ]; then
            echo "Found proprietary doc names outside docs/ directory:"; echo "$matches"; exit 1; fi
      - name: Scan for sensitive content
        run: |
          # Exclude quarantine folder, CI workflows, .agent-os, .codex, and known safe references
          if grep -RniE '(client_secret|service account|transfer hits|internal runbook|admin only)' \
            --exclude-dir=_quarantine-docs \
            --exclude-dir=.github \
            --exclude-dir=.agent-os \
            --exclude-dir=.codex \
            -- . \
            | grep -v 'README.md.*Admin Only.*private.*repository'; then
            echo "Found sensitive keywords in public repo"; exit 1; fi
