name: Guard public repo
on: [push, pull_request]
jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Scan for sensitive filenames
        run: |
          # Check for proprietary filenames, excluding known stub files
          if git ls-files | grep -v '^docs/' | grep -Eiq '(TECHNICAL_DOCUMENTATION|SCORING_|SYSTEM_GUIDE|DEVELOPER_GUIDE|EMAIL_CONTROL_PANEL|COLLABORATION_GUIDE|CI_CD|RELEASE_CHECKLIST|TESTING|TESTING_REFERENCE|EMAIL_PRIZE_REFERENCE)'; then
            echo "Found proprietary doc names outside docs/ directory"; exit 1; fi
      - name: Scan for sensitive content
        run: |
          # Exclude quarantine folder, CI workflows, and known safe references
          if grep -RniE '(client_secret|service account|transfer hits|internal runbook|admin only)' --exclude-dir=_quarantine-docs --exclude-dir=.github --exclude-dir=.agent-os -- . | grep -v 'README.md.*Admin Only.*private.*repository'; then
            echo "Found sensitive keywords in public repo"; exit 1; fi